version: '2'
services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

    web:
      build: .
      container_name: web
      command: python manage.py runserver 0.0.0.0:8000
      env_file: secrets_sigem_dev.env
      volumes:
        - .:/salesforceapp
      ports:
        - "8000:8000"
    
    
